# Project Key (required)
sonar.projectKey=bicnexp-file-clean

# Project Name (optional)
sonar.projectName=bicnexp-file-clean

# Comma-separated paths to directories with sources (required)
sonar.sources=docker,src

# Encoding of the source files (optional but recommended as default is ASCII)
sonar.sourceEncoding=UTF-8
