"""create dmf history tables

Revision ID: 0117e988992b
Revises:
Create Date: 2026-09-03 11:41:32.665505
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0117e988992b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmf_monitor_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_version', sa.Integer(), nullable=False),
    sa.Column('query_payload', sa.JSON(), nullable=False),
    sa.Column('collection_status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queried_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('upstream_total', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('successful_pages', sa.Integer(), nullable=False),
    sa.Column('failed_page', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('history_status', sa.String(length=32), nullable=False),
    sa.Column('history_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dmf_monitor_runs_collection_status'), 'dmf_monitor_runs', ['collection_status'], unique=False)
    op.create_index(op.f('ix_dmf_monitor_runs_query_fingerprint'), 'dmf_monitor_runs', ['query_fingerprint'], unique=False)
    op.create_table('dmf_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('monitor_run_id', sa.String(length=36), nullable=False),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('previous_baseline_id', sa.String(length=36), nullable=True),
    sa.Column('queried_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('raw_content_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('baseline_eligible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_run_id'], ['dmf_monitor_runs.id'], ),
    sa.ForeignKeyConstraint(['previous_baseline_id'], ['dmf_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_run_id')
    )
    op.create_index(op.f('ix_dmf_snapshots_queried_at'), 'dmf_snapshots', ['queried_at'], unique=False)
    op.create_index(op.f('ix_dmf_snapshots_query_fingerprint'), 'dmf_snapshots', ['query_fingerprint'], unique=False)
    op.create_table('dmf_baselines',
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['dmf_snapshots.id'], ),
    sa.PrimaryKeyConstraint('query_fingerprint'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_table('dmf_change_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('previous_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('business_key', sa.String(length=255), nullable=False),
    sa.Column('before_payload', sa.JSON(), nullable=True),
    sa.Column('after_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['dmf_snapshots.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['dmf_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_dmf_change_event_key')
    )
    op.create_index(op.f('ix_dmf_change_events_business_key'), 'dmf_change_events', ['business_key'], unique=False)
    op.create_index(op.f('ix_dmf_change_events_change_type'), 'dmf_change_events', ['change_type'], unique=False)
    op.create_index(op.f('ix_dmf_change_events_snapshot_id'), 'dmf_change_events', ['snapshot_id'], unique=False)
    op.create_table('dmf_snapshot_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('dmf_no', sa.String(length=255), nullable=True),
    sa.Column('applicant_name', sa.Text(), nullable=True),
    sa.Column('ingredient', sa.Text(), nullable=True),
    sa.Column('valid_date', sa.String(length=255), nullable=True),
    sa.Column('business_key', sa.String(length=255), nullable=True),
    sa.Column('identity_kind', sa.String(length=32), nullable=True),
    sa.Column('match_eligible', sa.Boolean(), nullable=False),
    sa.Column('unmatched_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['dmf_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dmf_snapshot_records_business_key', 'dmf_snapshot_records', ['business_key'], unique=False)
    op.create_index(op.f('ix_dmf_snapshot_records_snapshot_id'), 'dmf_snapshot_records', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dmf_snapshot_records_snapshot_id'), table_name='dmf_snapshot_records')
    op.drop_index('ix_dmf_snapshot_records_business_key', table_name='dmf_snapshot_records')
    op.drop_table('dmf_snapshot_records')
    op.drop_index(op.f('ix_dmf_change_events_snapshot_id'), table_name='dmf_change_events')
    op.drop_index(op.f('ix_dmf_change_events_change_type'), table_name='dmf_change_events')
    op.drop_index(op.f('ix_dmf_change_events_business_key'), table_name='dmf_change_events')
    op.drop_table('dmf_change_events')
    op.drop_table('dmf_baselines')
    op.drop_index(op.f('ix_dmf_snapshots_query_fingerprint'), table_name='dmf_snapshots')
    op.drop_index(op.f('ix_dmf_snapshots_queried_at'), table_name='dmf_snapshots')
    op.drop_table('dmf_snapshots')
    op.drop_index(op.f('ix_dmf_monitor_runs_query_fingerprint'), table_name='dmf_monitor_runs')
    op.drop_index(op.f('ix_dmf_monitor_runs_collection_status'), table_name='dmf_monitor_runs')
    op.drop_table('dmf_monitor_runs')
    # ### end Alembic commands ###